plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman

title: Ca Va Bien Aller
description: L'incroyable épreuve de tout un peuple
show_downloads: false
