plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman

title: CA VA BIEN ALLER
description: L'incroyable épreuve de tout un peuple
show_downloads: false

github:
  is_project_page: false

google_analytics: UA-162508966-1
